name: Deploy Vue3 Front

on:
  push:
    branches: 
        - main
        - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Vue App
        run: npm run build

      - name: Decode PEM file
        run: |
          echo "${{ secrets.PEM_KEY }}" | base64 -d > caboomlog.pem
          chmod 600 caboomlog.pem

      - name: Clean remote directory
        run: |
          ssh -i caboomlog.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo rm -rf /caboomlog/front-service/* && sudo chown -R ubuntu:ubuntu /caboomlog/front-service"

      - name: Upload dist folder
        run: |
          scp -i caboomlog.pem -o StrictHostKeyChecking=no -r app/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/caboomlog/front-service/

      - name: Set permissions for NGINX
        run: |
          ssh -i caboomlog.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo chown -R www-data:www-data /caboomlog/front-service && sudo chmod -R 755 /caboomlog/front-service"

      - name: Restart NGINX container
        run: |
          ssh -i caboomlog.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd /caboomlog && docker compose down nginx && docker compose up nginx -d"
