name: front-service ci/cd

on:
  push:
    branches:
      - main
      - develop

env:
  NODE_VERSION: 23.10.0

jobs:
  front-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/caboomlog-front-service:latest -f ./Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/caboomlog-front-service:latest
      
      - name: Deploy to ubuntu server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            
            sudo mkdir -p /caboomlog/nginx
            sudo mkdir -p /caboomlog/front-service
          
            echo "${{ secrets.NGINX_CONF }}" | sudo tee /caboomlog/nginx/nginx.conf > /dev/null
          
            cd /caboomlog
          
            if [ -z "$DOCKER_USERNAME" ]; then
              echo "DOCKER_USERNAME is empty! Setting manually..."
              export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
            fi
          
            echo "Using DOCKER_USERNAME=$DOCKER_USERNAME"
          
            DOCKER_USERNAME=${DOCKER_USERNAME} sudo docker compose -f docker-compose.yml stop nginx front-service || true
            DOCKER_USERNAME=${DOCKER_USERNAME} sudo docker compose -f docker-compose.yml rm -f nginx front-service || true
            DOCKER_USERNAME=${DOCKER_USERNAME} sudo docker compose -f docker-compose.yml pull nginx front-service
            DOCKER_USERNAME=${DOCKER_USERNAME} sudo docker compose -f docker-compose.yml up -d nginx front-service
