name: front-service ci/cd

on:
  push:
    branches:
      - main

jobs:
  front-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "==> Removing old files..."
            sudo rm -rf front-remote
            sudo mkdir front-remote
            cd ./front-remote
            
            echo "==> Cloning repository..."
            sudo git clone https://github.com/caboom-log/front-service.git
            cd ./front-service
            
            echo "==> Installing dependencies..."
            sudo npm install
            
            echo "==> Building frontend..."
            sudo npm run build
            
            echo "==> Setting permissions..."
            sudo chmod -R 755 /app/dist
            
            echo "==> Restarting NGINX..."
            sudo docker-compose restart nginx